language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python manage.py syncdb --noinput"
# command to run tests
script:
  - export DJANGO_SETTINGS_MODULE="echaloasuerte.settings.develop"
  - nosetests test_init.py . -v
