language: python
services:
  - mongodb
python:
  - "2.7"
#  - "3.4"
# command to install dependencies
addons:
    sauce_connect:
        username: "echaloasuerte"
        access_key: "966c755a-b4b0-42f9-80ec-5e5a0f0375ab"
install:
  - "pip install -r requirements.txt"
  - export DJANGO_SETTINGS_MODULE="echaloasuerte.settings.test"
  - "python manage.py syncdb --noinput"
# command to run tests
script:
  - nosetests test_init.py server/test -v
  - nosetests func_test -v
