language: python
services:
  - mongodb
python:
  - "2.7"
#  - "3.4"
# command to install dependencies
addons:
    sauce_connect:
        username: "pickforme"
        access_key: "d9f595a6-adce-4580-92b9-b12a05d73760"
install:
  - "pip install -r requirements.txt"
  - export DJANGO_SETTINGS_MODULE="echaloasuerte.settings.test"
  - "python manage.py syncdb --noinput"
# command to run tests
script:
  - nosetests test_init.py server/test -v
  - nosetests func_test -v
